<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceCategory;
use App\Support\DummyImage;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            [
                'Massage Tradisional',
                'massage-relaksasi',
                'Pijat khas Indonesia dengan tekanan lembut hingga sedang untuk melancarkan peredaran darah dan meredakan pegal.',
                'Massage Tradisional menggunakan teknik pijat khas Indonesia yang dipadukan dengan minyak pilihan. Pijatan diberikan secara menyeluruh mulai dari punggung, bahu, leher, hingga kaki untuk membantu tubuh lebih rileks setelah beraktivitas.',
                ['Melancarkan peredaran darah', 'Meredakan pegal dan nyeri otot', 'Mengurangi stres dan kelelahan', 'Meningkatkan kualitas tidur', 'Mengembalikan energi tubuh'],
                '60 menit',
                150000,
                'Harga dapat berbeda tergantung lokasi. Konsultasikan kebutuhan Anda dengan tim kami.',
                true,
                1,
                'massage-tradisional',
            ],
            [
                'Aromatherapy Massage',
                'massage-relaksasi',
                'Pijat relaksasi dengan aroma terapi esensial yang menenangkan pikiran dan tubuh.',
                'Aromatherapy Massage menggabungkan teknik pijat lembut dengan minyak esensial pilihan seperti lavender dan chamomile. Wangi aromaterapi membantu menenangkan pikiran sekaligus membuat tubuh lebih rileks.',
                ['Menenangkan pikiran dan emosi', 'Mengurangi kecemasan', 'Melancarkan peredaran darah', 'Menghilangkan rasa penat', 'Membuat tidur lebih nyenyak'],
                '60 menit',
                185000,
                null,
                true,
                2,
                'aromaterapi-massage',
            ],
            [
                'Deep Tissue Massage',
                'massage-relaksasi',
                'Pijat dengan tekanan lebih dalam untuk mengatasi ketegangan otot yang kronis.',
                'Deep Tissue Massage menggunakan tekanan lebih kuat dan teknik khusus untuk menjangkau lapisan otot yang lebih dalam. Perawatan ini cocok untuk Anda yang memiliki ketegangan otot akibat pekerjaan atau aktivitas berat.',
                ['Mengatasi ketegangan otot kronis', 'Mengurangi nyeri punggung dan leher', 'Memperbaiki postur tubuh', 'Meningkatkan fleksibilitas otot'],
                '60 menit',
                200000,
                null,
                false,
                3,
                'deep-tissue-massage',
            ],
            [
                'Pijat Refleksi',
                'massage-relaksasi',
                'Pijat pada titik refleksi kaki yang membantu menstimulasi organ tubuh secara alami.',
                'Pijat Refleksi menekankan pijatan pada titik-titik refleksi di telapak kaki yang berhubungan dengan organ tubuh. Teknik ini membantu mengembalikan keseimbangan tubuh dan meredakan rasa lelah.',
                ['Mengurangi rasa lelah', 'Melancarkan peredaran darah', 'Meringankan sakit kepala', 'Menyeimbangkan fungsi organ tubuh'],
                '45 menit',
                120000,
                null,
                false,
                4,
                'pijat-refleksi',
            ],
            [
                'Slimming Body Wrap',
                'slimming-body-care',
                'Perawatan body wrap untuk membantu mengencangkan kulit dan membentuk tubuh ideal.',
                'Slimming Body Wrap menggunakan ramuan khusus yang dibalut pada tubuh untuk membantu proses pembentukan tubuh. Perawatan ini membantu mengurangi rasa kurang nyaman di area perut, paha, dan lengan.',
                ['Membantu mengencangkan kulit', 'Mendukung program penurunan berat badan', 'Mengurangi rasa sesak di area tertentu', 'Membuat tubuh terasa lebih ringan'],
                '90 menit',
                250000,
                'Hasil terbaik diperoleh dengan program rutin minimal 6-10 kali perawatan.',
                true,
                5,
                'slimming-body-wrap',
            ],
            [
                'Program Slimming V-Shape',
                'slimming-body-care',
                'Program perawatan khusus untuk membantu membentuk kontur tubuh bagian atas.',
                'Program Slimming V-Shape dirancang untuk membantu membentuk kontur tubuh bagian atas agar terlihat lebih proporsional. Perawatan dipadukan dengan body wrap dan teknik pijat khusus.',
                ['Membantu membentuk kontur tubuh', 'Mengencangkan area lengan dan punggung', 'Meningkatkan rasa percaya diri', 'Mendukung gaya hidup sehat'],
                '90 menit',
                350000,
                null,
                true,
                6,
                'slimming-v-shape',
            ],
            [
                'Totok Wajah',
                'perawatan-wajah',
                'Teknik pijat wajah tradisional untuk meremajakan dan menyegarkan kulit wajah.',
                'Totok Wajah adalah teknik pijat wajah khas tradisional yang menstimulasi titik-titik saraf pada wajah. Perawatan ini membantu melancarkan peredaran darah sehingga wajah terlihat lebih segar dan kencang.',
                ['Wajah terasa lebih segar', 'Membantu mengencangkan kulit wajah', 'Melancarkan peredaran darah di wajah', 'Mengurangi rasa tegang di area kepala'],
                '45 menit',
                125000,
                null,
                false,
                7,
                'totok-wajah',
            ],
            [
                'Facial & Lulur Wajah',
                'perawatan-wajah',
                'Perawatan wajah lengkap dengan pembersihan, eksfoliasi, dan pelembap untuk kulit sehat.',
                'Facial & Lulur Wajah membersihkan kulit wajah secara menyeluruh mulai dari pembersihan, pengelupasan kulit mati, hingga pelembap. Perawatan ini cocok untuk menjaga kesehatan kulit wajah secara rutin.',
                ['Membersihkan pori-pori', 'Mengangkat sel kulit mati', 'Menjaga kelembapan kulit', 'Membuat wajah tampak bercahaya'],
                '60 menit',
                180000,
                null,
                false,
                8,
                'facial-lulur-wajah',
            ],
            [
                'Herbal Bath',
                'herbal-tradisional',
                'Berendam dengan ramuan herbal hangat untuk relaksasi dan melancarkan peredaran darah.',
                'Herbal Bath menggunakan air hangat yang dicampur rempah-rempah pilihan. Berendam dalam ramuan herbal membantu melemaskan otot, melancarkan peredaran darah, dan membuat tubuh terasa segar kembali.',
                ['Membantu melancarkan peredaran darah', 'Melemaskan otot yang tegang', 'Mengurangi pegal linu', 'Memberikan efek relaksasi menyeluruh'],
                '60 menit',
                175000,
                null,
                true,
                9,
                'herbal-bath',
            ],
            [
                'Lulur Rempah Tradisional',
                'herbal-tradisional',
                'Pengelupasan dan perawatan kulit dengan rempah tradisional untuk kulit halus.',
                'Lulur Rempah Tradisional menggunakan campuran rempah pilihan untuk mengangkat sel kulit mati sekaligus menutrisi kulit. Kulit terasa lebih halus, cerah, dan lembut setelah perawatan.',
                ['Mengangkat sel kulit mati', 'Menghaluskan dan melembutkan kulit', 'Mencerahkan kulit tubuh', 'Mengharumkan tubuh secara alami'],
                '90 menit',
                200000,
                null,
                false,
                10,
                'lulur-rempah',
            ],
            [
                'Pijat Ibu Hamil',
                'perawatan-pasca-melahirkan',
                'Pijat lembut khusus ibu hamil untuk mengurangi pegal dan menjaga kenyamanan.',
                'Pijat Ibu Hamil menggunakan teknik lembut yang aman untuk ibu hamil. Pijatan membantu mengurangi pegal di punggung dan kaki serta memberikan rasa nyaman selama masa kehamilan.',
                ['Mengurangi pegal saat hamil', 'Meredakan bengkak pada kaki', 'Meningkatkan kualitas tidur', 'Memberikan rasa nyaman dan tenang'],
                '60 menit',
                250000,
                'Perawatan dilakukan oleh terapis berpengalaman dan aman untuk kehamilan trimester kedua dan ketiga.',
                true,
                11,
                'pijat-ibu-hamil',
            ],
            [
                'Post Natal Care',
                'perawatan-pasca-melahirkan',
                'Perawatan menyeluruh untuk membantu pemulihan ibu setelah melahirkan.',
                'Post Natal Care adalah rangkaian perawatan khusus ibu pasca melahirkan, meliputi pijat pemulihan, perawatan perut, dan perawatan payudara. Perawatan membantu proses pemulihan dan menjaga kenyamanan ibu.',
                ['Membantu pemulihan tubuh ibu', 'Mengurangi perut kembung dan pegal', 'Mendukung kelancaran ASI', 'Memberikan rasa nyaman dan rileks'],
                '120 menit',
                300000,
                null,
                true,
                12,
                'post-natal-care',
            ],
            [
                'Perawatan Payudara & Pantang',
                'perawatan-pasca-melahirkan',
                'Perawatan tradisional untuk membantu kenyamanan ibu selama masa nifas.',
                'Perawatan Payudara & Pantang menggunakan metode tradisional yang membantu ibu selama masa nifas. Perawatan ini membantu kenyamanan dan mendukung proses pemulihan secara alami.',
                ['Mendukung kelancaran ASI', 'Mengurangi rasa tidak nyaman', 'Membantu proses pemulihan nifas', 'Merawat tubuh secara menyeluruh'],
                '90 menit',
                225000,
                null,
                false,
                13,
                'payudara-pantang',
            ],
            [
                'Homecare Massage',
                'homecare',
                'Layanan pijat relaksasi yang datang langsung ke rumah Anda.',
                'Homecare Massage menghadirkan terapis profesional ke rumah Anda. Cocok untuk Anda yang memiliki waktu terbatas atau membutuhkan perawatan dengan privasi penuh di rumah.',
                ['Nyaman dilakukan di rumah', 'Terapis profesional dan ramah', 'Hemat waktu perjalanan', 'Fleksibel dengan jadwal Anda'],
                '90 menit',
                350000,
                'Biaya layanan homecare sudah termasuk transport terapis.',
                false,
                14,
                'homecare-massage',
            ],
            [
                'Homecare Post Natal',
                'homecare',
                'Perawatan pasca melahirkan di rumah oleh terapis berpengalaman.',
                'Homecare Post Natal membantu ibu yang baru melahirkan untuk mendapatkan perawatan pemulihan tanpa harus bepergian. Terapis berpengalaman datang langsung ke rumah sesuai jadwal.',
                ['Pemulihan tanpa bepergian', 'Terapis khusus post natal', 'Jadwal fleksibel', 'Privasi dan kenyamanan di rumah'],
                '120 menit',
                500000,
                null,
                false,
                15,
                'homecare-post-natal',
            ],
        ];

        foreach ($services as [$name, $categorySlug, $short, $desc, $benefits, $duration, $price, $note, $featured, $order, $seed]) {
            $category = ServiceCategory::where('slug', $categorySlug)->first();

            Service::updateOrCreate(
                ['slug' => str()->slug($name)],
                [
                    'service_category_id' => $category?->id,
                    'name' => $name,
                    'short_description' => $short,
                    'description' => $desc,
                    'benefits' => $benefits,
                    'duration' => $duration,
                    'price' => $price,
                    'note' => $note,
                    'image' => DummyImage::store('services', $seed, 900, 600),
                    'alt_text' => $name,
                    'is_featured' => $featured,
                    'is_active' => true,
                    'sort_order' => $order,
                ]
            );
        }
    }
}
